# The name of the environment
name: unimod
# The relevent channels
channels:
- conda-forge
- bioconda
dependencies:
- r-base>=4.0
- r-optparse
- r-tidyverse
- bioconductor-brgenomics
- bioconductor-plyranges
- bioconductor-rtracklayer
